# Numpy基础

In [3]:
import array

In [4]:
arr= array.array("i",[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]= "jj"

TypeError: an integer is required (got type str)

In [8]:
arr.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Numpy.array

**创建array**

In [9]:
import numpy as np
nparr= np.array([i for i in range(10)])

In [10]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
nparr[5]= 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [12]:
nparr[5]= "machine learning"

ValueError: invalid literal for int() with base 10: 'machine learning'

## 查看和更改Numpy array中的数据类型

In [13]:
nparr.dtype    #dtype为 data type的缩写

dtype('int64')

In [14]:
nparr.astype("float32").dtype  #可以使用astype对array内的数据类型进行更改
# nparr.astype("double").dtype  #double 等于 float64

dtype('float32')

In [15]:
nparr.astype("int64").dtype

dtype('int64')

***当传入的值为浮点数时，用以存储int类型的nparr会自动进行隐式的类型转换，舍弃浮点数的小数部分***

In [16]:
nparr[5]= 5.74
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr= nparr.astype("float32")
nparr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [18]:
nparr[5]= 5.3434231313423111
nparr

array([0.       , 1.       , 2.       , 3.       , 4.       , 5.3434234,
       6.       , 7.       , 8.       , 9.       ], dtype=float32)

## numpy array的隐式类型转换

In [19]:
nparr2= np.array([1,"2",3.4])
nparr2

array(['1', '2', '3.4'], dtype='<U21')

In [20]:
nparr2= np.array([1,2,3.4])
nparr2

array([1. , 2. , 3.4])

In [21]:
nparr2= np.array([True,"2",3.4])
nparr2

array(['True', '2', '3.4'], dtype='<U5')

In [22]:
nparr2= np.array([True,False,3.4])
nparr2

array([1. , 0. , 3.4])

## 其他创建Numpy array的方法

In [23]:
# 创建一个所有元素都是0的数组
np.zeros(shape= (10,5),dtype= "int64")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
# 创建一个所有元素都是1的数组
np.ones(shape= (10,3),dtype= "str")

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [25]:
# 创建一个全部是指定值的数组
np.full(shape= (10,4),fill_value= 888)
np.full(shape= (10,4),fill_value= 666.0)

array([[666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.]])

In [26]:
# 创建一个对角线元素都是1的矩阵（单位矩阵）
np.eye(N= 10,M= 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## arange

In [27]:
# Python内置range方法
[i for i in range(0,10,2)] # 从0到10（不包括10），每隔两个数取一个

[0, 2, 4, 6, 8]

In [28]:
# Numpy的arange方法，括号内参数意义与Python内置的range方法参数意义一致
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [29]:
# range和arange的区别，步长是否可以传入浮点数
[i for i in range(0,10,0.5)]  #Python内置range步长不可接收浮点数

TypeError: 'float' object cannot be interpreted as an integer

In [32]:
np.arange(0,10,0.5) #arange可以接受传入浮点数类型步长

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## linspace

***linspace的作用在于，在指定区间内，取间隔相等的指定个数***

***对于linspace这个函数而言，终止点包含在取数范围内***

In [33]:
np.linspace(0,10,num= 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## random

***randint***

randint(low, high=None, size=None, dtype='l')

In [34]:
#代表0到3内的随机整数，不包括3（前闭后开区间），0为隐式指定
np.random.randint(3)

1

In [35]:
#代表0到10内的随机整数，不包括10（前闭后开区间）
np.random.randint(0,10)

6

In [36]:
#创建一个数组，size为元素个数，取数范围依然为前闭后开区间。
np.random.randint(0,10,size= 3)

array([4, 2, 5])

***seed 随机数种子***

***np.random.seed()***

In [37]:
#使用种子可以使同一方法不同行生成的随机数变得一样
np.random.seed(100)
np.random.randint(10,100,size= 10)

array([18, 34, 77, 97, 89, 58, 20, 62, 63, 76])

In [38]:
np.random.seed(100)
np.random.randint(10,100,size= 10)

array([18, 34, 77, 97, 89, 58, 20, 62, 63, 76])

***random.random 生成随机浮点数***

In [39]:
#创建一个随机浮点数数组，size用来指定数组元素个数，如不指定size参数，将生成一个随机数而不是一个数组
np.random.random(size= 10)

array([0.21010774, 0.4527399 , 0.87014264, 0.06368104, 0.62431189,
       0.52334774, 0.56229626, 0.00581719, 0.30742321, 0.95018431])

In [40]:
np.random.random()

0.12665423878983417

In [41]:
np.random.random((3,5)) #创建一个3行5列的数组（矩阵）

array([[0.07898787, 0.31135313, 0.63238359, 0.69935892, 0.64196495],
       [0.92002378, 0.29887635, 0.56874553, 0.17862432, 0.5325737 ],
       [0.64669147, 0.14206538, 0.58138896, 0.47918994, 0.38641911]])

***normal()函数,生成符合正态分布的随机浮点数（即均值为0，方差为1）***

In [42]:
np.random.normal()

-2.0724118580618414

In [43]:
np.random.normal(loc= 3,scale= 5,size= (10,3)) #loc参数表示均值，scale参数表示方差，size表示数组的形状

array([[-3.47719919,  0.67988208,  2.71486681],
       [ 4.37964868, 10.47257609,  5.83410319],
       [-8.51687131,  9.88500359, -2.93693409],
       [ 3.39696527,  3.53984313,  5.53475552],
       [ 8.6279468 , -2.04026242,  4.77414614],
       [-0.51334091,  3.56725566, -2.20566852],
       [-0.43299676, -9.79723791,  7.73155275],
       [ 6.95335826,  6.40000947,  6.5830291 ],
       [ 5.38852423, -0.33119966,  3.42240041],
       [ 1.30619753,  6.5296059 , -5.00880701]])

In [44]:
np.random.normal?

In [45]:
np.random?

In [46]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of numpy.random.mtrand.RandomState instance
    seed(self, seed=None)
    
    Reseed a legacy MT19937 BitGenerator
    
    Notes
    -----
    This is a convenience, legacy function.
    
    The best practice is to **not** reseed a BitGenerator, rather to
    recreate a new one. This method is here for legacy reasons.
    This example demonstrates best practice.
    
    >>> from numpy.random import MT19937
    >>> from numpy.random import RandomState, SeedSequence
    >>> rs = RandomState(MT19937(SeedSequence(123456789)))
    # Later, you want to restart the stream
    >>> rs = RandomState(MT19937(SeedSequence(987654321)))



## Numpy.array的基本操作

In [47]:
import numpy as np

In [48]:
x= np.arange(10,100,3)
x.shape

(30,)

### reshape

***使用reshape改变数组形状***

a.reshape(shape, order='C')

In [49]:
X= x.reshape(5,-1) 
X

array([[10, 13, 16, 19, 22, 25],
       [28, 31, 34, 37, 40, 43],
       [46, 49, 52, 55, 58, 61],
       [64, 67, 70, 73, 76, 79],
       [82, 85, 88, 91, 94, 97]])


***当填入-1时，Numpy会自动帮你计算在指定的行或列数的前提下，对应的列或行数，
需要注意的是，指定的行或列数需为整数，并能整除原数组的size（长乘以宽）***

In [50]:
x.shape

(30,)

In [51]:
x.ndim

1

In [52]:
x.reshape(5,6)

array([[10, 13, 16, 19, 22, 25],
       [28, 31, 34, 37, 40, 43],
       [46, 49, 52, 55, 58, 61],
       [64, 67, 70, 73, 76, 79],
       [82, 85, 88, 91, 94, 97]])

In [53]:
x.reshape(10,-1)

array([[10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43],
       [46, 49, 52],
       [55, 58, 61],
       [64, 67, 70],
       [73, 76, 79],
       [82, 85, 88],
       [91, 94, 97]])

In [54]:
#将一维向量转为一行n列矩阵
x.reshape(1,-1).ndim

2

### 基本属性

In [55]:
x.ndim #返回一个int型整数，表示数组的维数

1

In [56]:
X.ndim

2

In [57]:
X.shape #返回一个元组，表示行和列

(5, 6)

In [58]:
X.size #返回一个int型整数，表示数组的元素个数（长乘以宽）

30

### Numpy.array的数据访问

In [59]:
x

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [60]:
x[7]

31

In [61]:
x[-2]

94

In [62]:
#使用索引访问多维数组
X[0,1]
X[0:3,1:-1] #使用切片访问多维数组

array([[13, 16, 19, 22],
       [31, 34, 37, 40],
       [49, 52, 55, 58]])

In [63]:
X[::2,::2]# 使用切片步长访问多维数组

array([[10, 16, 22],
       [46, 52, 58],
       [82, 88, 94]])

In [64]:
#使用花式切片将多维数组反转
X[::-1,::-1]

array([[97, 94, 91, 88, 85, 82],
       [79, 76, 73, 70, 67, 64],
       [61, 58, 55, 52, 49, 46],
       [43, 40, 37, 34, 31, 28],
       [25, 22, 19, 16, 13, 10]])

***numpy中，对array数组切片实际上是对原数组的一种引用，如果改变了切片后数组的元素，对应的原数组中的元素也会改变。同样的，如果改变了原数组中的元素，对应的切片后的数组元素也会发生改变。***

In [65]:
subX= X[:2,:3]
subX[0,0]= 100
subX

array([[100,  13,  16],
       [ 28,  31,  34]])

In [66]:
X  #可以看到原数组的第0行第0列的元素也发生了改变

array([[100,  13,  16,  19,  22,  25],
       [ 28,  31,  34,  37,  40,  43],
       [ 46,  49,  52,  55,  58,  61],
       [ 64,  67,  70,  73,  76,  79],
       [ 82,  85,  88,  91,  94,  97]])

In [67]:
X[0,0]= 0
X

array([[ 0, 13, 16, 19, 22, 25],
       [28, 31, 34, 37, 40, 43],
       [46, 49, 52, 55, 58, 61],
       [64, 67, 70, 73, 76, 79],
       [82, 85, 88, 91, 94, 97]])

In [68]:
subX #可以发现subX的第0行第0列的元素也发生了改变

array([[ 0, 13, 16],
       [28, 31, 34]])

***如果想要创建一个与原数组无关的新切片数组，可以使用copy()方法***

In [69]:
subX= X[:2,:2].copy()
subX

array([[ 0, 13],
       [28, 31]])

In [70]:
subX[0,0]= 1
subX

array([[ 1, 13],
       [28, 31]])

In [71]:
X  #可以看出subX的改变已无法影响到原数组X

array([[ 0, 13, 16, 19, 22, 25],
       [28, 31, 34, 37, 40, 43],
       [46, 49, 52, 55, 58, 61],
       [64, 67, 70, 73, 76, 79],
       [82, 85, 88, 91, 94, 97]])

## 数组合并与分割

In [72]:
x= np.array([1,2,3])
y= np.array([3,2,1])

In [73]:
x

array([1, 2, 3])

In [74]:
y

array([3, 2, 1])

In [76]:
#拼接两个向量
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [77]:
#也可以拼接多个列表
np.concatenate([x,y,np.array([23,34,45])])

array([ 1,  2,  3,  3,  2,  1, 23, 34, 45])

In [79]:
A= np.array([[1,2,3],
             [3,4,5]])
A

array([[1, 2, 3],
       [3, 4, 5]])

In [80]:
#二位数组拼接
np.concatenate([A,A])

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5]])

In [81]:
#在列的维度上进行拼接
np.concatenate([A,A],axis= 1) #axis默认是0，代表从行的维度上进行拼接

array([[1, 2, 3, 1, 2, 3],
       [3, 4, 5, 3, 4, 5]])

In [83]:
#将向量和矩阵进行拼接
z= np.array([666,666,666])
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  3,   4,   5],
       [666, 666, 666]])

In [84]:
#拼接向量和矩阵可以不用预先reshape，使用stack替代,其中vstack表示从垂直方向的叠加，hstack表示从水平方向的叠加
np.vstack([A,z])

array([[  1,   2,   3],
       [  3,   4,   5],
       [666, 666, 666]])

In [88]:
#hstack
B= np.full(shape= (2,2),fill_value= 100)
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  3,   4,   5, 100, 100]])

### 分割

In [89]:
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.split(x,[3,7]) #将x分割，第一个分割点是3，第二个分割点是7

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [91]:
np.split(x,[5]) #将x分割成两段

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

***矩阵的分割***

In [94]:
A= np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
#矩阵在行上分割
np.split(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [100]:
#矩阵在列上进行分割
np.split(A,[2],axis= 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [101]:
#vsplit 垂直方向分割
np.vsplit(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [102]:
#hsplit 水平方向分割
np.hsplit(A,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

假设有一个（4 X 4)的机器学习数据集矩阵，前3列为特征值，后一列为目标向量

In [104]:
data= np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
#分割特征值和目标向量
X,y= np.hsplit(data,[-1])

In [106]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [107]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [109]:
#用切片取出y中元素
y[:,0]

array([ 3,  7, 11, 15])

## Numpy.array中的运算

给定一个向量，让向量中每一个数乘以2

a= (0,1,2)

a\*2= (0,2,4)

In [2]:
#如果在Python中使用list
n= 10
L= [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
#只是简单地将list复制了一次
L* 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
#要使用原生的语法实现list每个元素乘以2
A= []
for i in L:
    A.append(i* 2)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [16]:
#效率
%time 
n= 1000000
L= [i for i in range(n)]
A= []
for i in L:
    A.append(i* 2)

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.44 µs


In [2]:
%%time
#使用遍历
n= 1000000
L= [i for i in range(n)]
A= []
for i in L:
    A.append(i* 2)

CPU times: user 162 ms, sys: 36.5 ms, total: 198 ms
Wall time: 197 ms


In [1]:
%%time
#使用列表生成式
n= 1000000
L= [i for i in range(n)]
A= [i*2 for i in L]

CPU times: user 97 ms, sys: 32.2 ms, total: 129 ms
Wall time: 128 ms


使用Numpy工具的广播机制

In [1]:
%%time
#使用Numpy重复上面cell的操作，比原生的快了100倍以上
import numpy as np
L= np.arange(1000000)

CPU times: user 109 ms, sys: 7.93 ms, total: 117 ms
Wall time: 115 ms


In [9]:
%%time
A= 2 *L

CPU times: user 0 ns, sys: 4.07 ms, total: 4.07 ms
Wall time: 2.93 ms


In [8]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

## Universal Function

In [11]:
X= np.arange(1,16).reshape((3,5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
X+ 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [13]:
X -1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
X* 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [15]:
X/ 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [16]:
X// 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [17]:
X** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [18]:
X% 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [19]:
1/ X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [20]:
#求绝对值
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
#求正弦函数
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [22]:
#余弦函数
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [23]:
#正切函数
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [28]:
#同理，反三角函数也有相应的方法
np.arcsin(X)
np.arccos(X)
np.arctan(X)

/home/birch/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in arcsin
  
/home/birch/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in arccos
  This is separate from the ipykernel package so we can avoid doing imports until


array([[0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077],
       [1.40564765, 1.42889927, 1.44644133, 1.46013911, 1.47112767],
       [1.48013644, 1.48765509, 1.49402444, 1.49948886, 1.50422816]])

In [31]:
#求e的n次方
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [34]:
#求指定数的指定次幂
np.power(X,3)

array([[   1,    8,   27,   64,  125],
       [ 216,  343,  512,  729, 1000],
       [1331, 1728, 2197, 2744, 3375]])

In [40]:
#求对数值，如果只调用log表示求自然对数
np.log(X)
np.log2(X)
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [41]:
A= np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [43]:
B= np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [44]:
A+ B

array([[10, 11],
       [12, 13]])

In [45]:
A- B

array([[-10,  -9],
       [ -8,  -7]])

In [46]:
A* B

array([[ 0, 10],
       [20, 30]])

In [47]:
#矩阵点积
np.dot(A,B)

array([[10, 10],
       [50, 50]])

In [48]:
#等价于上一个cell
A.dot(B)

array([[10, 10],
       [50, 50]])

In [49]:
#矩阵转置
A.T

array([[0, 2],
       [1, 3]])

## 矩阵和向量的运算

In [50]:
A

array([[0, 1],
       [2, 3]])

In [56]:
v= np.arange(2,10,step= 5)
v

array([2, 7])

In [57]:
A+ v

array([[ 2,  8],
       [ 4, 10]])

由于一个向量和一个矩阵相加是没有意义的，可以将向量堆叠后再相加

In [58]:
np.vstack([v]* A.shape[0])

array([[2, 7],
       [2, 7]])

In [59]:
np.vstack([v]* A.shape[0])+ A

array([[ 2,  8],
       [ 4, 10]])

In [60]:
#tile方法,等价于上述的vstack方法
np.tile(v,(2,1))  #表示在行向量上堆叠两次，在列向量上只堆叠一次

array([[2, 7],
       [2, 7]])

In [61]:
np.tile(v,(2,1)) + A

array([[ 2,  8],
       [ 4, 10]])

In [62]:
v* A

array([[ 0,  7],
       [ 4, 21]])

In [63]:
#Numpy自动将v视作行向量
v.dot(A)

array([14, 23])

In [64]:
#Numpy自动将v视作列向量
A.dot(v)

array([ 7, 25])

## 矩阵的逆

In [70]:
A

array([[0, 1],
       [2, 3]])

In [66]:
#求A的逆矩阵，（逆矩阵：用原矩阵乘以逆矩阵，其结果为单位矩阵,并不是所有的矩阵都有逆矩阵，至少要是一个方阵）
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [71]:
invA= np.linalg.inv(A)

In [73]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [74]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [89]:
X= np.arange(10).reshape(2,5)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
#对非方阵的矩阵求逆矩阵，将会报错
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [91]:
#在机器学习中，很多时候需要对矩阵求逆矩阵，但很多时候该矩阵不一定是方阵，Numpy提供了求伪逆矩阵的方法
pinvX= np.linalg.pinv(X)
pinvX

array([[-3.20000000e-01,  1.20000000e-01],
       [-1.80000000e-01,  8.00000000e-02],
       [-4.00000000e-02,  4.00000000e-02],
       [ 1.00000000e-01, -1.38777878e-17],
       [ 2.40000000e-01, -4.00000000e-02]])

In [92]:
#原矩阵乘以伪逆矩阵的结果为一个单位矩阵,除对角线外，其余地方的数都近乎0，这是因为计算机的浮点误差造成的
X.dot(pinvX)

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 8.88178420e-16,  1.00000000e+00]])