In [1]:
import numpy as np
L= np.random.random(100)
L

array([0.00741852, 0.88232953, 0.54960868, 0.04760796, 0.3532348 ,
       0.44447599, 0.08212331, 0.51277112, 0.85626306, 0.19470915,
       0.85351018, 0.36388807, 0.26587664, 0.35210561, 0.65224117,
       0.06426102, 0.71902071, 0.2876057 , 0.42963834, 0.83942357,
       0.82627849, 0.63603198, 0.36583606, 0.76093667, 0.72019669,
       0.80132751, 0.10677654, 0.44891931, 0.46585357, 0.41352418,
       0.80745622, 0.53713606, 0.54153889, 0.06033081, 0.7760349 ,
       0.27506292, 0.46309604, 0.68080085, 0.60831995, 0.57395765,
       0.17451794, 0.50322017, 0.85546352, 0.8341153 , 0.5716551 ,
       0.39147027, 0.07745307, 0.46576437, 0.40624524, 0.15814747,
       0.79140494, 0.26428095, 0.11702494, 0.56376089, 0.49349859,
       0.4825574 , 0.70228305, 0.12261773, 0.9463827 , 0.73858573,
       0.97165904, 0.30551826, 0.46528427, 0.22585765, 0.79681116,
       0.0241646 , 0.2724171 , 0.11952965, 0.96969439, 0.62799578,
       0.87617566, 0.34342823, 0.89829227, 0.4539464 , 0.57344

In [3]:
sum(L)

49.62979412574523

In [4]:
np.sum(L)

49.62979412574524

两者效率对比

In [5]:
big_array= np.random.rand(1000000)
%time sum(big_array)
%time np.sum(big_array)

CPU times: user 150 ms, sys: 12 µs, total: 150 ms
Wall time: 149 ms
CPU times: user 1.72 ms, sys: 0 ns, total: 1.72 ms
Wall time: 1.17 ms


499585.3489065337

## numpy中的聚合操作

In [6]:
np.min(L)

0.007418517401777458

In [7]:
np.max(L)

0.9889826388566509

**也可以使用面向对象的方式进行操作,但推荐使用np.方法 这样的方式进行调用**

In [8]:
L.min()

0.007418517401777458

In [9]:
L.max()

0.9889826388566509

In [10]:
L.sum()

49.62979412574524

In [12]:
X= np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.sum(X)

120

In [17]:
#如果需要对矩阵每一行求和，需要指定axis参数,当axis=1表示在行上，axis=0表示在列上
np.sum(X,axis= 1)
np.sum(X,axis= 0)

array([24, 28, 32, 36])

In [18]:
#矩阵中所有元素的乘积
np.prod(X)

0

In [19]:
np.prod(X+ 1)

20922789888000

In [21]:
#求平均值和中位数
np.mean(X)
np.median(X)

7.5

In [22]:
#百分位数
np.percentile(big_array,q= 50) #q= 50表示求百分之50分位数，即有50%的数值小于这个数

0.49941318690981806

In [23]:
#求方差
np.var(big_array)

0.0833299916659682

In [24]:
#求标准差
np.std(big_array)

0.28866934659912924

## Numpy中的arg运算（索引）

In [1]:
import numpy as np
X= np.random.normal(0,1,size= 1000000)

In [3]:
X.shape

(1000000,)

In [5]:
np.min(X)

-4.732859139695716

如果想要获得X的最小值可以使用np.min(X),那么如果想获得最小值所在的位置，也就是最小值的索引呢？

In [4]:
np.argmin(X)

929742

In [6]:
X[929742]

-4.732859139695716

In [7]:
#最大值的索引
np.argmax(X)

102034

In [8]:
#返回排序后的索引
np.argsort(X)

array([929742, 243987, 726824, ..., 672897, 169847, 102034])

## 排序和使用索引

In [38]:
x= np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
#先打乱X的顺序
np.random.shuffle(x)
x

array([ 2,  9, 12, 14, 10,  4,  1,  5, 13,  6,  8, 11,  7,  3,  0])

In [16]:
#对X进行排序
np.sort(X)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

对矩阵进行排序

In [36]:
X= np.random.randint(low= 1,high= 10,size= (2,5))
X

array([[9, 7, 2, 9, 7],
       [2, 1, 5, 3, 1]])

In [33]:
#默认对每一行进行排序
X.sort()
X

array([[1, 2, 3, 3, 8],
       [4, 6, 7, 7, 9]])

In [37]:
#在列上排序
X.sort(axis= 0)
X

array([[2, 1, 2, 3, 1],
       [9, 7, 5, 9, 7]])

In [44]:
x

array([ 2,  9, 12, 14, 10,  4,  1,  5, 13,  6,  8, 11,  7,  3,  0])

In [40]:
#找到一个排序时设置的标定点
np.partition(x,3)  #在3前面的值都比3小，在3后面的值都比3大，但前后不一定是有序的

array([ 1,  0,  2,  3,  4,  5,  6,  7, 10, 12,  8, 11,  9, 13, 14])

In [41]:
#同样，partition也有arg方法，返回索引
np.argpartition(x,3)

array([ 6, 14,  0, 13,  5,  7,  9, 12,  4,  2, 10, 11,  1,  8,  3])

## Fancy indexing

In [32]:
import numpy as np
x= np.arange(16)
np.random.shuffle(x)
x

array([ 6, 15,  8, 13, 14, 11,  5,  3,  2,  1,  4,  0,  9,  7, 10, 12])

In [8]:
x[1]
x[0:10:2]

array([ 1, 14, 11,  3, 12])

In [9]:
#花式索引
index= [1,3,4]
x[index]

array([15, 10, 11])

In [10]:
#同样支持多维
index= np.array([[1,2],
                [3,1]])
x[index]

array([[15, 14],
       [10, 15]])

In [15]:
index= np.array([[
                  [1,2],
                  [3,1],
                  [3,4],
                  [1,4]]])
x[index]

array([[[15, 14],
        [10, 15],
        [10, 11],
        [15, 11]]])

In [33]:
x= x.reshape(4,-1)
x

array([[ 6, 15,  8, 13],
       [14, 11,  5,  3],
       [ 2,  1,  4,  0],
       [ 9,  7, 10, 12]])

In [19]:
#同时指定行和列
row= [0,1,3]
col= [2,3,1]
x[row,col]

array([14,  2, 13])

In [20]:
x[0,col]

array([14, 10, 15])

In [21]:
x[:2,col]

array([[14, 10, 15],
       [ 3,  2,  5]])

In [22]:
x[row,3]

array([10,  2,  9])

In [23]:
x[row,:3]

array([[ 1, 15, 14],
       [11,  5,  3],
       [ 7, 13,  6]])

In [24]:
#同样可以使用布尔值指定需要提取的行或列，其中true表示提取，false表示不提取
col= [True,False,True,False]
x[:2,col]

array([[ 1, 14],
       [11,  3]])

In [25]:
row= [True,False,True,False]
x[row,:2]

array([[ 1, 15],
       [12,  8]])

## Numpy中的比较

In [38]:
x= x.flatten()

In [39]:
x

array([ 6, 15,  8, 13, 14, 11,  5,  3,  2,  1,  4,  0,  9,  7, 10, 12])

In [43]:
x< 3
x[x< 3]

array([False, False, False, False, False, False, False, False,  True,
        True, False,  True, False, False, False, False])

In [44]:
x<= 3

array([False, False, False, False, False, False, False,  True,  True,
        True, False,  True, False, False, False, False])

In [49]:
#可以代入加减乘除等法则，组成更复杂的条件
x[np.exp(x)== np.log2(x)]

/home/birch/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log2
  


array([], dtype=int64)

In [48]:
x[np.power(x,2)== x* 2]

array([2, 0])

In [50]:
#可以直接根据条件来聚合运算
np.sum(x<3)

3

In [51]:
np.mean(x>3)

0.75

In [52]:
np.std(x*3 == x**2)

0.33071891388307384

In [53]:
#计算数组中的非零元素个数
np.count_nonzero(x>3) #False为0，True为1

12

In [54]:
#判断数组是否存在某个元素满足给定条件
np.any(x== 0)

True

In [55]:
np.any(x< 0)

False

In [56]:
#判断数组是否所有元素都满足给定条件
np.all(x< 10)

False

In [57]:
np.all(x<30)

True

In [65]:
X= np.arange(16).reshape(4,-1)
np.random.shuffle(X)
X

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [66]:
np.all(X> 0)

False

In [67]:
#查看X有多少偶数
np.sum(X % 2== 0)  #使用sum原理，True为1，False为0，sum函数即求所有布尔值的和

8

In [68]:
#沿行或列来计算
np.sum(X % 2== 0, axis= 1) #row

array([2, 2, 2, 2])

In [69]:
np.sum(X % 2 ==0 ,axis= 0) #columns

array([4, 0, 4, 0])

In [72]:
#与
np.sum((X> 3) & (X < 10))

6

In [74]:
#或
np.sum((X> 3) | (X < 10))

16

In [76]:
#非
np.sum(~(X> 3))

4

In [79]:
np.sum((X<= 3))

4

In [70]:
np.all(X> 0, axis= 1)

array([ True,  True,  True, False])

In [71]:
np.any(X <= 3,axis= 0)

array([ True,  True,  True,  True])

In [85]:
X= X.reshape(4,-1)
X

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [86]:
X[X[:,3] % 3 == 0,:]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])