In [1]:
import array

In [2]:
arr= array.array("i",[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]= "jj"

TypeError: an integer is required (got type str)

# Numpy.array

创建array

In [42]:
import numpy as np
nparr= np.array([i for i in range(10)])

In [14]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5]= 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [16]:
nparr[5]= "machine learning"

ValueError: invalid literal for int() with base 10: 'machine learning'

## 查看和更改Numpy array中的数据类型

In [43]:
nparr.dtype    #dtype为 data type的缩写

dtype('int64')

In [44]:
nparr.astype("float32").dtype  #可以使用astype对array内的数据类型进行更改
# nparr.astype("double").dtype  #double 等于 float64

dtype('float32')

In [27]:
nparr.astype("int64").dtype

dtype('int64')

In [45]:
#当传入的值为浮点数时，用以存储int类型的nparr会自动进行隐式的类型转换，舍弃浮点数的小数部分
nparr[5]= 5.74
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
nparr= nparr.astype("float32")
nparr

array([0.       , 1.       , 2.       , 3.       , 4.       , 5.3434234,
       6.       , 7.       , 8.       , 9.       ], dtype=float32)

In [51]:
nparr[5]= 5.3434231313423111
nparr

array([0.       , 1.       , 2.       , 3.       , 4.       , 5.3434234,
       6.       , 7.       , 8.       , 9.       ], dtype=float32)

## numpy array的隐式类型转换

In [54]:
nparr2= np.array([1,"2",3.4])
nparr2

array(['1', '2', '3.4'], dtype='<U21')

In [55]:
nparr2= np.array([1,2,3.4])
nparr2

array([1. , 2. , 3.4])

In [57]:
nparr2= np.array([True,"2",3.4])
nparr2

array(['True', '2', '3.4'], dtype='<U5')

In [59]:
nparr2= np.array([True,False,3.4])
nparr2

array([1. , 0. , 3.4])

## 其他创建Numpy array的方法

In [74]:
# 创建一个所有元素都是0的数组
np.zeros(shape= (10,5),dtype= "int64")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [75]:
# 创建一个所有元素都是1的数组
np.ones(shape= (10,3),dtype= "str")

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [78]:
# 创建一个全部是指定值的数组
np.full(shape= (10,4),fill_value= 888)
np.full(shape= (10,4),fill_value= 666.0)

array([[666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.]])

In [76]:
# 创建一个对角线元素都是1的矩阵（单位矩阵）
np.eye(N= 10,M= 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## arange

In [80]:
# Python内置range方法
[i for i in range(0,10,2)] # 从0到10（不包括10），每隔两个数取一个

[0, 2, 4, 6, 8]

In [82]:
# Numpy的arange方法，括号内参数意义与Python内置的range方法参数意义一致
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [83]:
# range和arange的区别，步长是否可以传入浮点数
[i for i in range(0,10,0.5)]  #Python内置range步长不可接收浮点数

TypeError: 'float' object cannot be interpreted as an integer

In [85]:
np.arange(0,10,0.5) #arange可以接受传入浮点数类型步长

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])