# Numpy基础

In [1]:
import array

In [2]:
arr= array.array("i",[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]= "jj"

TypeError: an integer is required (got type str)

## Numpy.array

**创建array**

In [42]:
import numpy as np
nparr= np.array([i for i in range(10)])

In [14]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5]= 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [16]:
nparr[5]= "machine learning"

ValueError: invalid literal for int() with base 10: 'machine learning'

## 查看和更改Numpy array中的数据类型

In [43]:
nparr.dtype    #dtype为 data type的缩写

dtype('int64')

In [44]:
nparr.astype("float32").dtype  #可以使用astype对array内的数据类型进行更改
# nparr.astype("double").dtype  #double 等于 float64

dtype('float32')

In [27]:
nparr.astype("int64").dtype

dtype('int64')

***当传入的值为浮点数时，用以存储int类型的nparr会自动进行隐式的类型转换，舍弃浮点数的小数部分***

In [45]:
nparr[5]= 5.74
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
nparr= nparr.astype("float32")
nparr

array([0.       , 1.       , 2.       , 3.       , 4.       , 5.3434234,
       6.       , 7.       , 8.       , 9.       ], dtype=float32)

In [51]:
nparr[5]= 5.3434231313423111
nparr

array([0.       , 1.       , 2.       , 3.       , 4.       , 5.3434234,
       6.       , 7.       , 8.       , 9.       ], dtype=float32)

## numpy array的隐式类型转换

In [54]:
nparr2= np.array([1,"2",3.4])
nparr2

array(['1', '2', '3.4'], dtype='<U21')

In [55]:
nparr2= np.array([1,2,3.4])
nparr2

array([1. , 2. , 3.4])

In [57]:
nparr2= np.array([True,"2",3.4])
nparr2

array(['True', '2', '3.4'], dtype='<U5')

In [59]:
nparr2= np.array([True,False,3.4])
nparr2

array([1. , 0. , 3.4])

## 其他创建Numpy array的方法

In [74]:
# 创建一个所有元素都是0的数组
np.zeros(shape= (10,5),dtype= "int64")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [75]:
# 创建一个所有元素都是1的数组
np.ones(shape= (10,3),dtype= "str")

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [78]:
# 创建一个全部是指定值的数组
np.full(shape= (10,4),fill_value= 888)
np.full(shape= (10,4),fill_value= 666.0)

array([[666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.],
       [666., 666., 666., 666.]])

In [76]:
# 创建一个对角线元素都是1的矩阵（单位矩阵）
np.eye(N= 10,M= 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## arange

In [80]:
# Python内置range方法
[i for i in range(0,10,2)] # 从0到10（不包括10），每隔两个数取一个

[0, 2, 4, 6, 8]

In [82]:
# Numpy的arange方法，括号内参数意义与Python内置的range方法参数意义一致
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [83]:
# range和arange的区别，步长是否可以传入浮点数
[i for i in range(0,10,0.5)]  #Python内置range步长不可接收浮点数

TypeError: 'float' object cannot be interpreted as an integer

In [85]:
np.arange(0,10,0.5) #arange可以接受传入浮点数类型步长

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## linspace

***linspace的作用在于，在指定区间内，取间隔相等的指定个数***

***对于linspace这个函数而言，终止点包含在取数范围内***

In [89]:
np.linspace(0,10,num= 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## random

***randint***

randint(low, high=None, size=None, dtype='l')

In [112]:
#代表0到3内的随机整数，不包括3（前闭后开区间），0为隐式指定
np.random.randint(3)

1

In [103]:
#代表0到10内的随机整数，不包括10（前闭后开区间）
np.random.randint(0,10)

3

In [127]:
#创建一个数组，size为元素个数，取数范围依然为前闭后开区间。
np.random.randint(0,10,size= 3)

array([1, 5, 7])

***seed 随机数种子***

***np.random.seed()***

In [133]:
#使用种子可以使同一方法不同行生成的随机数变得一样
np.random.seed(100)
np.random.randint(10,100,size= 10)

array([18, 34, 77, 97, 89, 58, 20, 62, 63, 76])

In [137]:
np.random.seed(100)
np.random.randint(10,100,size= 10)

array([18, 34, 77, 97, 89, 58, 20, 62, 63, 76])

***random.random 生成随机浮点数***

In [146]:
#创建一个随机浮点数数组，size用来指定数组元素个数，如不指定size参数，将生成一个随机数而不是一个数组
np.random.random(size= 10)

array([0.13671513, 0.17192781, 0.50305449, 0.05585289, 0.29766707,
       0.92771357, 0.38659638, 0.46212547, 0.57862899, 0.1139206 ])

In [158]:
np.random.random()

0.8596048874892304

In [165]:
np.random.random((3,5)) #创建一个3行5列的数组（矩阵）

array([[0.80938403, 0.92580965, 0.89988772, 0.43454589, 0.02134634],
       [0.78510132, 0.18258255, 0.57643742, 0.35635898, 0.76286615],
       [0.53281217, 0.36405572, 0.41126815, 0.24624624, 0.11203632]])

***normal()函数,生成符合正态分布的随机浮点数（即均值为0，方差为1）***

In [166]:
np.random.normal()

0.6830267133931089

In [171]:
np.random.normal(loc= 3,scale= 5,size= (10,3)) #loc参数表示均值，scale参数表示方差，size表示数组的形状

array([[ 6.34739475, -4.64283117,  8.37319728],
       [13.12795033, -3.06426457,  6.48632527],
       [ 8.59231464, -1.18860271,  2.75099916],
       [ 8.40473102, -0.84547588,  1.74198141],
       [-5.90447001,  5.47933708, -1.57003738],
       [ 7.64933604,  4.85351468,  7.24266506],
       [-2.36790423,  1.380749  ,  2.22305048],
       [ 9.56373618, 15.45192235, -0.1458507 ],
       [ 0.35547603,  2.12877448, -1.13752724],
       [-0.78530724,  6.74994637, 10.03838283]])

In [173]:
np.random.normal?

In [174]:
np.random?

In [176]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of numpy.random.mtrand.RandomState instance
    seed(self, seed=None)
    
    Reseed a legacy MT19937 BitGenerator
    
    Notes
    -----
    This is a convenience, legacy function.
    
    The best practice is to **not** reseed a BitGenerator, rather to
    recreate a new one. This method is here for legacy reasons.
    This example demonstrates best practice.
    
    >>> from numpy.random import MT19937
    >>> from numpy.random import RandomState, SeedSequence
    >>> rs = RandomState(MT19937(SeedSequence(123456789)))
    # Later, you want to restart the stream
    >>> rs = RandomState(MT19937(SeedSequence(987654321)))

